name: linux-eic-shell

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        run: |
          PREFIX=${PWD}/install
          # install ip6 repo
          git clone https://github.com/eic/ip6.git eic_ip6
          pushd eic_ip6
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=${PREFIX}
          cmake --build build -- install
          popd
          # install this repo
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=${PREFIX}
          cmake --build build -- install
          # link ip6 into install
          ln -sf ../ip6/ip6 ${PREFIX}/share/ecce/ip6
    - uses: actions/upload-artifact@v3
      with:
        name: geometry
        path: install/
        if-no-files-found: error

  convert-to-gdml:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: geometry
        path: install/
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        setup: install/setup.sh
        run: |
          mkdir -p geo
          python scripts/convert_to_gdml.py --compact ${DETECTOR_PATH}/${DETECTOR}.xml --output geo/${DETECTOR}.gdml
    - uses: actions/upload-artifact@v3
      with:
        name: ecce.gdml
        path: geo/
        if-no-files-found: error

  convert-to-tgeo:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: geometry
        path: install/
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        setup: install/setup.sh
        run: |
          mkdir -p geo
          dd_web_display --output geo/${DETECTOR}.root ${DETECTOR_PATH}/${DETECTOR}.xml
    - uses: actions/upload-artifact@v3
      with:
        name: ecce.root
        path: geo/
        if-no-files-found: error

  check-overlap-tgeo:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: geometry
        path: install/
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        setup: install/setup.sh
        run: |
          mkdir -p doc
          sed -i '/<fiber/,+6d' ${DETECTOR_PATH}/compact/ecal_barrel_interlayers.xml
          sed -i '/<fiber/,+4d' ${DETECTOR_PATH}/ip6/far_forward/ZDC_Ecal_WSciFi.xml
          checkOverlaps -c ${DETECTOR_PATH}/${DETECTOR_CONFIG}.xml | tee doc/overlap_check_tgeo.out
          noverlaps="$(grep -c ovlp doc/overlap_check_tgeo.out || true)"
          if [[ "${noverlaps}" -gt "0" ]] ; then echo "${noverlaps} overlaps found!" && false ; fi

  check-overlap-geant4:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: geometry
        path: install/
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        setup: install/setup.sh
        run: |
          mkdir -p doc
          sed -i '/<fiber/,+6d' ${DETECTOR_PATH}/compact/ecal_barrel_interlayers.xml
          sed -i '/<fiber/,+4d' ${DETECTOR_PATH}/ip6/far_forward/ZDC_Ecal_WSciFi.xml
          python scripts/checkOverlaps.py -c ${DETECTOR_PATH}/${DETECTOR_CONFIG}.xml | tee doc/overlap_check_geant4.out
          noverlaps="$(grep -c GeomVol1002 doc/overlap_check_geant4.out || true)"
          if [[ "${noverlaps}" -gt "0" ]] ; then echo "${noverlaps} overlaps found!" && false ; fi

  trigger-detector-benchmarks:
    runs-on: ubuntu-latest
    needs: [check-overlap-tgeo, check-overlap-geant4]
    steps:
    - uses: eic/trigger-gitlab-ci@v2
      id: trigger
      with:
        url: https://eicweb.phy.anl.gov
        project_id: 399
        token: ${{ secrets.EICWEB_DETECTOR_BENCHMARK_TRIGGER }}
        ref_name: master
        variables: |
          JUGGLER_DETECTOR_REPOSITORYURL=${{ github.repositoryUrl }}
          JUGGLER_DETECTOR_VERSION=${{ github.ref_name }}
    - uses: peter-evans/commit-comment@v2
      with:
        body: |
          Detector benchmarks started at ${{ steps.trigger.outputs.web_url }}
